version: '3'

services:
  frontend:
    build: .
    container_name: frontend
    ports:
      - 80:80/tcp
      - 443:443/tcp
    environment:
      IS_SINGLE_CERTIFICATE: 1

      CERTBOT_EMAIL: slymahel@gmail.com
    volumes:
      - ./conf.d:/etc/nginx/user.conf.d:ro
      - ./letsencrypt:/etc/letsencrypt
